#!/bin/sh

# Ottieni il path degli script da fare andare dopo un merge
RED='\033[0;31m'
NC='\033[0m'
FILE=.env
if [ -f "$FILE" ]; then
  source $FILE
  echo $TRANSFORM_LINKS_PATHS_DIR
else
  echo "${RED}>>>>___ATTENZIONE___<<<<${NC} Arianna!!!!\nIl file $FILE non esiste. Copia il path della cartella contenente gli script post-merge in un file .env nella cartella $PWD"
  exit 1
fi

# Ottieni l'ultimo messaggio di commit
last_commit_message=$(git log -1 --pretty=%B)

# Controlla se ci troviamo sul branch 'main'
if [ $(git rev-parse --abbrev-ref HEAD) = "main" ]; then
  # Controlla se il merge proviene da un fetch dal repository remoto
  if [[ $last_commit_message == *"--local"* ]]; then
    # Log per indicare che è stato effettuato il merge di un branch remoto
    echo "Merge effettuato da un fetch dal repository locale"
  else
    # Merge dovuto a modifiche remote
    bun $TRANSFORM_LINKS_PATHS_DIR
  fi
fi
